<a href="https://colab.research.google.com/github/ayobamialimi/DataScienceEcosystem/blob/main/multivariate_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
# I want to handle the NAN, get the median of the bedrooms
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [ ]:
# fill the na value
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [ ]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
# create linear regression

# call the linear regression model
reg = linear_model.LinearRegression()

# train the model with your dataset
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [ ]:
`reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
reg.intercept_

221323.00186540396

In [ ]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [ ]:
reg.predict([[3000,3,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([611518.37838246])

# Multivariate regression model on hiring data

In [23]:
df2 = pd.read_csv("hiring.csv")
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [24]:
#rename some columns
df2.rename(columns={'test_score(out of 10)': 'test_score', 'interview_score(out of 10)': 'interview_score', 'salary($)':'salary' }, inplace=True)

In [25]:
df2

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [26]:
# I want to handle the NAN, get the median of the bedrooms
import math
median_testscore = math.floor(df2.test_score.median())
median_testscore

8

In [27]:
# fill the na value

df2.test_score = df2.test_score.fillna(median_testscore)

In [28]:
df2.loc[0,'experience']= 'four'
df2.loc[1,'experience']= 'six'
df2

experience  test_score  interview_score  salary
0       four         8.0                9   50000
1        six         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [34]:
# Dictionary mapping string values to numeric values
mapping = {'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5, 'six': 6, 'six': 6, 'seven': 7, 'eight': 8, 'ten': 10, 'eleven': 11}

#replace the string with the numeric values
df2.replace(mapping, inplace=True)
df2

experience  test_score  interview_score  salary
0           4         8.0                9   50000
1           6         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [35]:
# create linear regression

# call the linear regression model
reg = linear_model.LinearRegression()

# train the model with your dataset
reg.fit(df2[['experience', 'test_score', 'interview_score']], df2.salary)

LinearRegression()

In [38]:
reg.predict([[6,8,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([55907.01651258])